version: 2
jobs:
  node:
    working_directory: ~/hotminute
    docker:
      - image: 'circleci/node:12'
    steps:
      - checkout
      - restore_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}'
      - restore_cache:
          key: 'node-v1-{{ checksum "package.json" }}-{{ arch }}'
      - run: yarn install
      - save_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}'
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: 'node-v1-{{ checksum "package.json" }}-{{ arch }}'
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/hotminute
          paths:
            - node_modules
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  android:
    working_directory: ~/hotminute/android
    environment: 
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    docker:
      - image: 'circleci/android:api-28-node'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "04:7a:ad:d7:39:8d:da:22:2f:8d:d0:02:37:47:00:96"
      - checkout:
          path: ~/hotminute
      - attach_workspace:
          at: ~/hotminute
      - restore_cache:
          key: 'bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}'
      - run: 
          name: Install Gems
          command: bundle install
      - save_cache:
          key: 'bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}'
          paths:
            - vendor/bundle
      - run:
          name: Deploy Beta
          command: fastlane $FASTLANE_LANE
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: output
  ios:
    macos:
      xcode: 11.5.0
    working_directory: ~/hotminute
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    shell: /bin/bash --login -o pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "04:7a:ad:d7:39:8d:da:22:2f:8d:d0:02:37:47:00:96"
      - checkout
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.5" > ~/.ruby-version
      - restore_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}'
      - restore_cache:
          key: 'node-v1-{{ checksum "package.json" }}-{{ arch }}'
      - run: yarn install
      - save_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}'
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: 'node-v1-{{ checksum "package.json" }}-{{ arch }}'
          paths:
            - node_modules
      - restore_cache:
          key: 'bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}'
      - run:
          name: Install Gems
          command: bundle install
          working_directory: ios
      - save_cache:
          key: 'bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}'
          paths:
            - vendor/bundle
      - run:
          name: Install Distribution Certificates and Profiles
          command: bundle exec fastlane match appstore --readonly
          working_directory: ios
      - run:
          name: Install Development Certificates and Profiles
          command: bundle exec fastlane match development --readonly
          working_directory: ios
      - run:
          name: Deploy Beta Build
          command: bundle exec fastlane $FASTLANE_LANE
          working_directory: ios
      - store_test_results:
          path: ios/test-results
      - store_artifacts:
          path: ios/test-results
      - store_artifacts:
          path: output
workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      - ios:
          requires:
            - node
